services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=chemtech_default"
      - "traefik.http.routers.green-api.rule=PathPrefix(`/test-green-api`)"
      - "traefik.http.routers.green-api.entrypoints=web"
      - "traefik.http.routers.green-api.priority=100"
      - "traefik.http.services.green-api.loadbalancer.server.port=3000"
    networks:
      - default
      - chemtech_default

networks:
  chemtech_default:
    external: true